version: '3'

services:
  web:
    image: "${PROJECT_IMAGE}"
    container_name: data_visualization_web_1
    command: bash -c "python3 manage.py migrate --noinput &&
                      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8008:8000"
    volumes:
      - ./:/ ./
    restart: always
    environment:
     DATA_URL: 'http://minerals-ua.info/mapviewer/geolmapeng.html'
    depends_on:
      - db
  db:
    image: postgres:9.6
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      LC_ALL: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_USER: "psql"
      POSTGRES_DB: "psql"
      PGDATA: "/var/lib/postgresql/data/db/"


volumes:
    postgres_data:
    data_visualization:
