# Generated by Django 3.0.6 on 2020-05-22 20:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('year', models.DateField()),
            ],
        ),
    ]
